use_frameworks!

platform :ios, '9.0'

target 'JQPerformanceMonitor_Example' do
  pod 'JQPerformanceMonitor', :path => '../'

  target 'JQPerformanceMonitor_Tests' do
    inherit! :search_paths

    
  end
end
